### ISSUE TITLE
[PiP] Player unexpected error crash

### ISSUE THREAD

**Issue by iChun** [iChun/IssueTracker-Mods#11]
java.lang.NullPointerException: Unexpected error
    at net.minecraft.client.entity.EntityPlayerSP.func_70093_af(EntityPlayerSP.java:449)
    at net.minecraft.client.renderer.RenderGlobal.isMovingNow(RenderGlobal.java:3260)
    at net.minecraft.client.renderer.RenderGlobal.isMoving(RenderGlobal.java:3242)
    at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:2148)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1508)
    at pip.common.core.PiPInfo.renderIntoFramebuffer(PiPInfo.java:179)
    at pip.common.core.TickHandlerClient.onRenderTick(TickHandlerClient.java:155)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_70_TickHandlerClient_onRenderTick_RenderTickEvent.invoke(.dynamic)

**Comment by iChun** [comment]
Optifine crash
