### ISSUE TITLE
(1.12.2)(PortalGun) crash when trying to create a portal

### ISSUE THREAD

**Issue by 0Navis0** [iChun/IssueTracker-Mods#118]
I get this crash when I try to create a portal, the crash occurs at each time I try to reload the world. I suspect an incompability with Optifine since it's a problem of rendering. https://pastebin.com/htE8RGVC

**Comment by 777unlock777** [comment]
https://pastebin.com/LT4ww3F2

also had this 
>>
Description: Batching chunks
 
java.lang.NoSuchFieldError: field_189564_r
    at me.ichun.mods.ichunutil.common.module.worldportals.client.render.world.chunk.ListedRenderChunkWorldPortal.func_178581_b(ListedRenderChunkWorldPortal.java:71)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:119)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:47)
    at java.lang.Thread.run(Thread.java:745)
>>

**Comment by iChun** [comment]
Optifine crash
