### ISSUE TITLE
[Keygrip-Mocap] I keep crashing...

### ISSUE THREAD

**Issue by MythikiX** [iChun/IssueTracker-Mods#15]
I'm not gonna lie, Mocap is a really good mod and has a lot of solo machinima making potential. I wanna do that myself, but the problem is whenever I create a second action, it CRASHES! Hopefully you can fix this or tell me what to do if I installed it incorrectly. Here's the crash report:

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 4/4/15 9:01 AM
Description: Rendering screen

java.lang.NoSuchMethodError: java.lang.Integer.compare(II)I
    at us.ichun.mods.keygrip.common.scene.action.Action.compareTo(Action.java:450)
    at java.util.Arrays.mergeSort(Arrays.java:1144)
    at java.util.Arrays.sort(Arrays.java:1079)
    at java.util.Collections.sort(Collections.java:115)
    at us.ichun.mods.keygrip.client.gui.window.WindowNewAction.elementTriggered(WindowNewAction.java:137)
    at us.ichun.mods.ichunutil.client.gui.window.element.ElementButton.onClick(ElementButton.java:64)
    at us.ichun.mods.ichunutil.client.gui.window.Window.onClick(Window.java:200)
    at us.ichun.mods.ichunutil.client.gui.window.IWorkspace.drawWindows(IWorkspace.java:125)
    at us.ichun.mods.keygrip.client.gui.GuiWorkspace.func_73863_a(GuiWorkspace.java:147)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:461)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1078)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1048)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
    at net.minecraft.client.main.Main.main(SourceFile:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at us.ichun.mods.keygrip.common.scene.action.Action.compareTo(Action.java:450)
    at java.util.Arrays.mergeSort(Arrays.java:1144)
    at java.util.Arrays.sort(Arrays.java:1079)
    at java.util.Collections.sort(Collections.java:115)
    at us.ichun.mods.keygrip.client.gui.window.WindowNewAction.elementTriggered(WindowNewAction.java:137)
    at us.ichun.mods.ichunutil.client.gui.window.element.ElementButton.onClick(ElementButton.java:64)
    at us.ichun.mods.ichunutil.client.gui.window.Window.onClick(Window.java:200)
    at us.ichun.mods.ichunutil.client.gui.window.IWorkspace.drawWindows(IWorkspace.java:125)
    at us.ichun.mods.keygrip.client.gui.GuiWorkspace.func_73863_a(GuiWorkspace.java:147)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:461)

-- Screen render details --
Details:
    Screen name: us.ichun.mods.keygrip.client.gui.GuiWorkspace
    Mouse location: Scaled: (480, 360). Absolute: (961, 358)
    Screen size: Scaled: (960, 540). Absolute: (1920, 1080). Scale factor of 2

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['Govnah'/16, l='MpServer', x=-41.31, y=40.40, z=295.08]]
    Chunk stats: MultiplayerChunkCache: 417, 417
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: 0.00,30.00,-75.00 - World: (0,30,-75), Chunk: (at 0,1,5 in 0,-5; contains blocks 0,0,-80 to 15,255,-65), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Level time: 16047934 game time, 9759695244 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 25 total; [EntityTrail['unknown'/64, l='MpServer', x=-41.31, y=40.40, z=295.08], EntityPainting['Painting'/38, l='MpServer', x=-184.03, y=15.00, z=150.00], EntityPainting['Painting'/40, l='MpServer', x=-184.03, y=15.00, z=163.00], EntityPainting['Painting'/38, l='MpServer', x=-184.03, y=15.00, z=150.00], EntityPainting['Painting'/22, l='MpServer', x=-71.00, y=15.00, z=263.03], EntityPainting['Painting'/24, l='MpServer', x=-71.00, y=15.00, z=283.97], EntityPainting['Painting'/31, l='MpServer', x=-84.00, y=15.00, z=283.97], EntityPainting['Painting'/30, l='MpServer', x=-84.00, y=15.00, z=263.03], EntityPainting['Painting'/34, l='MpServer', x=72.00, y=15.00, z=263.03], EntityPainting['Painting'/35, l='MpServer', x=85.00, y=15.00, z=263.03], EntityPainting['Painting'/33, l='MpServer', x=72.00, y=15.00, z=283.97], EntityPlayerSP['Govnah'/16, l='MpServer', x=-41.31, y=40.40, z=295.08], EntityPainting['Painting'/37, l='MpServer', x=85.00, y=15.00, z=283.97], EntityPainting['Painting'/40, l='MpServer', x=-184.03, y=15.00, z=163.00], EntityPainting['Painting'/24, l='MpServer', x=-71.00, y=15.00, z=283.97], EntityPainting['Painting'/22, l='MpServer', x=-71.00, y=15.00, z=263.03], EntityPainting['Painting'/40, l='MpServer', x=-184.03, y=15.00, z=163.00], EntityPainting['Painting'/31, l='MpServer', x=-84.00, y=15.00, z=283.97], EntityPainting['Painting'/30, l='MpServer', x=-84.00, y=15.00, z=263.03], EntityPainting['Painting'/37, l='MpServer', x=85.00, y=15.00, z=283.97], EntityPainting['Painting'/35, l='MpServer', x=85.00, y=15.00, z=263.03], EntityPainting['Painting'/34, l='MpServer', x=72.00, y=15.00, z=263.03], EntityPainting['Painting'/33, l='MpServer', x=72.00, y=15.00, z=283.97], EntityPainting['Painting'/40, l='MpServer', x=-184.03, y=15.00, z=163.00], EntityPainting['Painting'/38, l='MpServer', x=-184.03, y=15.00, z=150.00]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:351)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2488)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:367)
    at net.minecraft.client.main.Main.main(SourceFile:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.8
    Operating System: Mac OS X (x86_64) version 10.10.2
    Java Version: 1.6.0_65, Apple Inc.
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
    Memory: 269025440 bytes (256 MB) / 642441216 bytes (612 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.10 FML v8.0.69.1353 Minecraft Forge 11.14.1.1353 6 mods loaded, 6 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{8.0.69.1353} [Forge Mod Loader](forge-1.8-11.14.1.1353.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{11.14.1.1353} [Minecraft Forge](forge-1.8-11.14.1.1353.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    iChunUtil{5.2.0} [iChunUtil](iChunUtil-5.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BackTools{5.0.0} [BackTools](BackTools-5.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Keygrip{5.0.0} [Keygrip](Keygrip-5.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Loaded coremods (and transformers): 
    Launched Version: 1.8-Forge11.14.1.1353
    LWJGL: 2.9.2
    OpenGL: Intel Iris Pro OpenGL Engine GL version 2.1 INTEL-10.2.46, Intel Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: No
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: [Traditional_Beauty_18v2]
Current Language: English (US)
Profiler Position: N/A (disabled)
```

**Comment by iChun** [comment]
You need to update java, it has a minimum requirement of java 7.

**Comment by MythikiX** [comment]
Okay I just updated Java to version 8. But it's still not working... Oh I forgot to ask, do I need to download the JRE file or the JDK file?

**Comment by iChun** [comment]
Updating Java on a Mac has different steps. You probably didn't do it right.
