### ISSUE TITLE
Gravity Gun 5.0.0 crashes client when picking up a Neotech mod block.

### ISSUE THREAD

**Issue by kreezxil** [iChun/IssueTracker-Mods#20]
crash report: https://paste.ee/p/tPNuJ
fml-client-latest: https://paste.ee/p/6uEQW

Feature Request:
Ability to blacklist mods from the gravity gun.

**Comment by iChun** [comment]
java.lang.NullPointerException: Rendering entity in world
    at net.minecraft.world.World.func_175701_a(World.java:216)
    at net.minecraft.world.World.func_180495_p(World.java:831)
    at com.dyonovan.neotech.client.modelfactory.models.ModelBlock.<init>(ModelBlock.java:36)
    at com.dyonovan.neotech.client.modelfactory.models.ModelBlock.handleBlockState(ModelBlock.java:95)
    at net.minecraft.client.renderer.BlockRendererDispatcher.func_175022_a(BlockRendererDispatcher.java:153)
    at us.ichun.mods.ichunutil.client.render.entity.RenderBlock.func_76986_a(RenderBlock.java:99)
    at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:370)
    at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:327)
    at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:294)
    at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:631)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1294)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1207)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1032)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
    at net.minecraft.client.main.Main.main(SourceFile:120)

**Comment by kreezxil** [comment]
are you implying it's actually neotech?

**Comment by iChun** [comment]
I'm posting the stack trace here so in case your paste expires... It's not necessarily neotech, since the NPE's in a vanilla function. I'll have to look see when I get time

**Comment by kreezxil** [comment]
Cool, thanks. :)

**Comment by iChun** [comment]
A bit late on this (bit more than a year) but I think it's probably neotech passing in a null argument. I'm not too sure, it's been a while.
