### ISSUE TITLE
[PiP] Botania crash

### ISSUE THREAD

**Issue by iChun** [iChun/IssueTracker-Mods#27]
https://github.com/iChun/iChunUtil/issues/101

java.lang.NullPointerException: Unexpected error
    at net.minecraft.client.entity.EntityPlayerSP.func_70093_af(EntityPlayerSP.java:449)
    at vazkii.botania.client.core.handler.MultiblockRenderHandler.onWorldRenderLast(MultiblockRenderHandler.java:56)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_704_MultiblockRenderHandler_onWorldRenderLast_RenderWorldLastEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:261)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1354)
    at pip.common.core.PiPInfo.renderIntoFramebuffer(PiPInfo.java:179)
    at pip.common.core.TickHandlerClient.onRenderTick(TickHandlerClient.java:155)

**Comment by Shahelion** [comment]
If not resolved, is the specific cause at least known?

**Comment by iChun** [comment]
Oh, right. I forgot to tag @Vazkii in this. I've not managed to look at the code that causes this yet as I've not been doing any development involving this area (or any development at all actually) as of late. It does not seem crazy prevalent (I think), so it was never marked as high priority. 

This causes an issue in isSneaking though so I'm not sure what would be the cause.

**Comment by iChun** [comment]
https://github.com/iChun/IssueTracker-Mods/issues/31#issuecomment-262423495
