### ISSUE TITLE
[PiP] Sending packets during render causes crash.

### ISSUE THREAD

**Issue by iChun** [iChun/IssueTracker-Mods#3]
2014-07-01 23:02:03 [INFO] [STDERR] java.lang.NullPointerException
2014-07-01 23:02:03 [INFO] [STDERR] at cpw.mods.fml.client.FMLClientHandler.sendPacket(FMLClientHandler.java:511)
2014-07-01 23:02:03 [INFO] [STDERR] at cpw.mods.fml.common.network.PacketDispatcher.sendPacketToServer(PacketDispatcher.java:38)
2014-07-01 23:02:03 [INFO] [STDERR] at emasher.sockets.client.ClientPacketHandler.requestDirectionData(ClientPacketHandler.java:297)
2014-07-01 23:02:03 [INFO] [STDERR] at emasher.sockets.pipes.TileDirectionChanger.func_70312_q(TileDirectionChanger.java:19)
2014-07-01 23:02:03 [INFO] [STDERR] at net.minecraft.world.chunk.Chunk.func_76604_a(Chunk.java:1036)
2014-07-01 23:02:03 [INFO] [STDERR] at net.minecraft.world.World.func_72837_a(World.java:2927)
2014-07-01 23:02:03 [INFO] [STDERR] at net.minecraft.world.chunk.Chunk.func_76597_e(Chunk.java:992)
2014-07-01 23:02:03 [INFO] [STDERR] at net.minecraft.world.ChunkCache.func_72796_p(ChunkCache.java:115)
2014-07-01 23:02:03 [INFO] [STDERR] at net.minecraft.client.renderer.WorldRenderer.func_78907_a(WorldRenderer.java:206)
2014-07-01 23:02:03 [INFO] [STDERR] at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1574)
2014-07-01 23:02:03 [INFO] [STDERR] at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1129)
2014-07-01 23:02:03 [INFO] [STDERR] at pip.common.core.PiPInfo.renderIntoFramebuffer(PiPInfo.java:174)
2014-07-01 23:02:03 [INFO] [STDERR] at pip.common.core.TickHandlerClient.preRenderTick(TickHandlerClient.java:144)
2014-07-01 23:02:03 [INFO] [STDERR] at pip.common.core.TickHandlerClient.tickStart(TickHandlerClient.java:34)
2014-07-01 23:02:03 [INFO] [STDERR] at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:28)
2014-07-01 23:02:03 [INFO] [STDERR] at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:122)
2014-07-01 23:02:03 [INFO] [STDERR] at cpw.mods.fml.common.FMLCommonHandler.onRenderTickStart(FMLCommonHandler.java:372)

**Comment by iChun** [comment]
Fixed.
