### ISSUE TITLE
[PiP] Crashing with Optifine.

### ISSUE THREAD

**Issue by iChun** [iChun/IssueTracker-Mods#5]
[01:47:35 INFO]: Client> java.lang.NullPointerException: Unexpected error
[01:47:35 INFO]: Client>        at net.minecraft.client.entity.EntityPlayerSP.func_70093_af(EntityPlayerSP.java:449)
[01:47:35 INFO]: Client>        at net.minecraft.client.renderer.RenderGlobal.isMovingNow(RenderGlobal.java:3247)
[01:47:35 INFO]: Client>        at net.minecraft.client.renderer.RenderGlobal.isMoving(RenderGlobal.java:3229)
[01:47:35 INFO]: Client>        at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:2143)
[01:47:35 INFO]: Client>        at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1484)
[01:47:35 INFO]: Client>        at pip.common.core.PiPInfo.renderIntoFramebuffer(PiPInfo.java:174)
[01:47:35 INFO]: Client>        at pip.common.core.TickHandlerClient.onRenderTick(TickHandlerClient.java:149)
create a new version of this paste

**Comment by filipejsfreitas** [comment]
Null pointers are so hard to fix specially in these cases where you don't really have the source or even control of what you are interacting with. Yes yes, I know, mcp can help you with the source part of it but still :/

BTW, that 'create a new version of this paste' means you want me to give you the full log or is it just a note for yourself?

**Comment by iChun** [comment]
Copy pasta problem.

**Comment by Mallander** [comment]
I'm getting a similar error using OptiFine with a custom mod, Have you managed to figure out a fix for this?

[12:26:14] [Client thread/FATAL]: Unreported exception thrown!
java.lang.NullPointerException
at net.minecraft.client.entity.EntityPlayerSP.func_70093_af(EntityPlayerSP.java:449) ~[blk.class:?]
at net.minecraft.client.renderer.RenderGlobal.isMovingNow(RenderGlobal.java:3285) ~[bma.class:?]
at net.minecraft.client.renderer.RenderGlobal.isMoving(RenderGlobal.java:3267) ~[bma.class:?]
at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:2159) ~[bma.class:?]
at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1514) ~[blt.class:?]
at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1301) ~[blt.class:?]
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) ~[bao.class:?]
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
