### ISSUE TITLE
[PiP] Crash (Don't know what else to say)

### ISSUE THREAD

**Issue by DoctorNefario** [iChun/IssueTracker-Mods#6]
http://pastebin.com/2zFULeUQ

**Comment by iChun** [comment]
Ah right this issue. Redownload the mod. It was hotfixed last night.

**Comment by LeoJonson** [comment]
crash report
---- Minecraft Crash Report ----
// Don't do that.

Time: 7/23/14 5:44 PM
Description: Rendering screen

java.lang.IllegalStateException: Already tesselating!
    at net.minecraft.client.renderer.Tessellator.func_78371_b(Tessellator.java:219)
    at net.minecraft.client.renderer.Tessellator.func_78382_b(Tessellator.java:212)
    at net.minecraft.client.gui.GuiMainMenu.func_73970_b(GuiMainMenu.java:479)
    at net.minecraft.client.gui.GuiMainMenu.func_73971_c(GuiMainMenu.java:540)
    at net.minecraft.client.gui.GuiMainMenu.func_73863_a(GuiMainMenu.java:568)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:945)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:835)
    at net.minecraft.client.main.Main.main(SourceFile:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.client.renderer.Tessellator.func_78371_b(Tessellator.java:219)
    at net.minecraft.client.renderer.Tessellator.func_78382_b(Tessellator.java:212)
    at net.minecraft.client.gui.GuiMainMenu.func_73970_b(GuiMainMenu.java:479)
    at net.minecraft.client.gui.GuiMainMenu.func_73971_c(GuiMainMenu.java:540)
    at net.minecraft.client.gui.GuiMainMenu.func_73863_a(GuiMainMenu.java:568)

-- Screen render details --
Details:
    Screen name: net.minecraft.client.gui.GuiMainMenu
    Mouse location: Scaled: (0, 239). Absolute: (0, 0)
    Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2
Stacktrace:
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:945)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:835)
    at net.minecraft.client.main.Main.main(SourceFile:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.2
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_65, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 718627728 bytes (685 MB) / 1279787008 bytes (1220 MB) up to 7603748864 bytes (7251 MB)
    JVM Flags: 3 total; -Xms256M -Xmx8157M -XX:PermSize=256m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.03 FML v7.2.217.1161 Minecraft Forge 10.12.2.1161 10 mods loaded, 10 mods active
    mcp{9.03} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    FML{7.2.217.1161} [Forge Mod Loader](forge-1.7.2-10.12.2.1161-mc172.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Forge{10.12.2.1161} [Minecraft Forge](forge-1.7.2-10.12.2.1161-mc172.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    iChunUtil{3.3.0} [iChunUtil](iChunUtil-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    PiP{3.0.4} [PiP](PiP-3.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    bspkrsCore{6.11} [bspkrsCore]([1.7.2]bspkrsCore-universal-6.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Baubles{1.0.0.13} [Baubles](Baubles-1.7.2-1.0.0.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ForgeMultipart{1.1.0.289} [Forge Multipart](ForgeMultipart-1.7.2-1.1.0.289-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    McMultipart{1.1.0.289} [Minecraft Multipart Plugin](ForgeMultipart-1.7.2-1.1.0.289-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ForgeMicroblock{1.1.0.289} [Forge Microblocks](ForgeMultipart-1.7.2-1.1.0.289-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Launched Version: 1.7.2
    LWJGL: 2.9.0
    OpenGL: GeForce GTX 650 Ti/PCIe/SSE2 GL version 4.3.0, NVIDIA Corporation
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: [Misa]
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: ~~ERROR~~ NullPointerException: null
    Anisotropic Filtering: Off (1)
