### ISSUE TITLE
[1.10.2][PortalGun] Rendering Issue AMD graphics

### ISSUE THREAD

**Issue by sscards55** [iChun/IssueTracker-Mods#87]
For some reason my game is rendering portals like this:
![2017-05-05_17 51 21](https://cloud.githubusercontent.com/assets/5591207/25768749/4d083172-31bf-11e7-8549-27018c6dd186.png)
Same world modpack and computer except with integrated graphics:
![2017-05-05_17 40 04](https://cloud.githubusercontent.com/assets/5591207/25768767/717e104e-31bf-11e7-906d-69363da9e69b.png)

**Comment by iChun** [comment]
Anything in the console for the messed up graphics?

**Comment by sscards55** [comment]
```
[20:09:46] [Client thread/INFO] [STDERR]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: java.lang.RuntimeException: Error creating shader: Fragment shader failed to compile with the following errors:
ERROR: 0:1: error(#263) "Precision qualifier" is not supported prior to GLSL version 1.30
ERROR: error(#273) 1 compilation errors.  No code generated


[20:09:46] [Client thread/INFO] [STDERR]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at me.ichun.mods.ichunutil.client.render.ShaderHelper.createShader(ShaderHelper.java:148)
[20:09:46] [Client thread/INFO] [STDERR]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at me.ichun.mods.ichunutil.client.render.ShaderHelper.createProgram(ShaderHelper.java:90)
[20:09:46] [Client thread/INFO] [STDERR]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at me.ichun.mods.portalgun.client.render.TileEntityRendererPortalMaster.drawFrontShader(TileEntityRendererPortalMaster.java:330)
[20:09:46] [Client thread/INFO] [STDERR]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at me.ichun.mods.portalgun.client.render.TileEntityRendererPortalMaster.drawPortalBorderAndOutline(TileEntityRendererPortalMaster.java:199)
[20:09:46] [Client thread/INFO] [STDERR]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at me.ichun.mods.portalgun.client.render.TileEntityRendererPortalMaster.renderTileEntityAt(TileEntityRendererPortalMaster.java:141)
[20:09:46] [Client thread/INFO] [STDERR]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at me.ichun.mods.portalgun.client.render.TileEntityRendererPortalMaster.func_180535_a(TileEntityRendererPortalMaster.java:37)
[20:09:46] [Client thread/INFO] [STDERR]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:147)
[20:09:46] [Client thread/INFO] [STDERR]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:125)
[20:09:46] [Client thread/INFO] [STDERR]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:701)
[20:09:46] [Client thread/INFO] [STDERR]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1315)
[20:09:46] [Client thread/INFO] [STDERR]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
[20:09:46] [Client thread/INFO] [STDERR]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
[20:09:46] [Client thread/INFO] [STDERR]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
[20:09:46] [Client thread/INFO] [STDERR]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
[20:09:46] [Client thread/INFO] [STDERR]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at net.minecraft.client.main.Main.main(SourceFile:124)
[20:09:46] [Client thread/INFO] [STDERR]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:09:46] [Client thread/INFO] [STDERR]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[20:09:46] [Client thread/INFO] [STDERR]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20:09:46] [Client thread/INFO] [STDERR]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[20:09:46] [Client thread/INFO] [STDERR]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[20:09:46] [Client thread/INFO] [STDERR]: [me.ichun.mods.ichunutil.client.render.ShaderHelper:createShader:156]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[20:09:46] [Client thread/ERROR] [iChunUtil]: Error: No shaders attached to current program 

[20:09:46] [Client thread/ERROR]: ########## GL ERROR ##########
[20:09:46] [Client thread/ERROR]: @ Post render
[20:09:46] [Client thread/ERROR]: 1281: Invalid value
```
This only shows up one time per instance.
When the portal first tries to render.

**Comment by iChun** [comment]
This helps. I'll see what I can do when I can

**Comment by GirafiStudios** [comment]
Can confirm, this happens on both of my computers with AMD graphics.

**Comment by NathanDreamweaver** [comment]
I can also confirm this happens. Really hope it gets fixed. @iChun any progress done?

**Comment by Flexico** [comment]
Also happens with Intel integrated graphics on my laptop. :(

**Comment by Gammaboy45** [comment]
It happens to me too, but I also noticed that holding another device causes the portal obstruction lines to render underneath the character sheet. I don't know whether this applies to the AMD graphics card glitch or if it is the same for a "correct" portal texture.
![what is this](https://user-images.githubusercontent.com/29964045/27937290-99cf01e2-627b-11e7-9a7b-9dd31476b07b.png)

**Comment by Flexico** [comment]
I turned off "fancy portal rendering" in my config options and now it works pretty well! Try that, guys.

**Comment by SamuelWAnderson45** [comment]
@Flexico That solved it for me as well. Though it's of course just a workaround, I would love to see an actual fix.

Also, what is the actual visual difference between fancy/non-fancy portals?

**Comment by Flexico** [comment]
@LordSamanon Pretty sure the fancy portals have the wavy, holographic kind of edges instead of just a plain ellipse.

**Comment by neoshifter39** [comment]
Hey This just started happening for me. The last time i installed this mod this didnt happen i have amd graphics and this didnt happen before. I think it is the mod and not the graphics. (i like fancy better.)

**Comment by iChun** [comment]
@modmuss50 reports this is fixed in version 7.0.1. Reopen a new issue if it's not

**Comment by SamuelWAnderson45** [comment]
@iChun Is it possible to have this fix backported to 1.10.2? I'm running a server and definitely can't make the upgrade to 1.12

**Comment by iChun** [comment]
This issue was a result of two bugs, but you should be able to fix it if
you replace the portal.fsh in 1.10.2's PG with the one in version 7.0.1

**Comment by iChun** [comment]
Let me know if that fixes it for you though, if it does it might be worthwhile making an update on curseforge.com for it.

**Comment by SamuelWAnderson45** [comment]
I'll give it a try

**Comment by SamuelWAnderson45** [comment]
Well, after having trouble getting Minecraft to even run (unrelated), I can confirm that it is fixed!

Thanks @iChun
