### ISSUE TITLE
[Gravity Gun] 1.10.2 Looking straight up/down ladders while holding Gravity Gun causes the game to crash.

### ISSUE THREAD

**Issue by ScytheIronclaw** [iChun/IssueTracker-Mods#93]
When holding the Gravity Gun and looking straight up or down a set of ladders, the game will crash.

Minecraft Version: 1.10.2
Forge Version: 12.18.3.2297
Gravity Gun Mod Version: 6.0.1

Crash Report:

> ---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreMod (Aroma1997Core-1.9.4-1.1.1.2.jar)
  IC2core (industrialcraft-2-2.6.210-ex110.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.10.2-1.2.0c.jar)
  DummyPlugin (ForgeEndertech-1.10.2-1.3.3.0-build.0055.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.9.jar)
  LoadingPlugin (Quark-r1.1-70.jar)
  RebornCoreASM (RebornCore-1.10.2-2.13.6.142-universal.jar)
  LoadingPlugin (AdFinders-1.10.2-1.1.2.0-build.0055.jar)
  AstralCore (astralsorcery-1.4.1.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 6/5/17 3:48 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at me.ichun.mods.gravitygun.common.gravitygun.GravityGunHelper.canGrab(GravityGunHelper.java:186)
	at me.ichun.mods.gravitygun.client.render.ItemRenderGravityGun.renderModel(ItemRenderGravityGun.java:166)
	at me.ichun.mods.ichunutil.client.model.item.ModelBaseWrapper.func_188616_a(ModelBaseWrapper.java:116)
	at net.minecraft.client.renderer.RenderItem.func_175045_a(RenderItem.java:169)
	at net.minecraft.client.renderer.RenderItem.func_175036_a(RenderItem.java:141)
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:204)
	at net.minecraft.client.renderer.RenderItem.func_184394_a(RenderItem.java:418)
	at net.minecraft.client.renderer.RenderItem.func_184392_a(RenderItem.java:381)
	at net.minecraft.client.renderer.ItemRenderer.func_187462_a(ItemRenderer.java:83)
	at net.minecraft.client.renderer.ItemRenderer.func_187457_a(ItemRenderer.java:478)
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:365)
	at net.minecraft.client.renderer.EntityRenderer.renderHand(EntityRenderer.java:1038)
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:982)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1918)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1574)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1347)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at me.ichun.mods.gravitygun.common.gravitygun.GravityGunHelper.canGrab(GravityGunHelper.java:186)
	at me.ichun.mods.gravitygun.client.render.ItemRenderGravityGun.renderModel(ItemRenderGravityGun.java:166)
	at me.ichun.mods.ichunutil.client.model.item.ModelBaseWrapper.func_188616_a(ModelBaseWrapper.java:116)
	at net.minecraft.client.renderer.RenderItem.func_175045_a(RenderItem.java:169)
	at net.minecraft.client.renderer.RenderItem.func_175036_a(RenderItem.java:141)
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:204)
	at net.minecraft.client.renderer.RenderItem.func_184394_a(RenderItem.java:418)
	at net.minecraft.client.renderer.RenderItem.func_184392_a(RenderItem.java:381)
	at net.minecraft.client.renderer.ItemRenderer.func_187462_a(ItemRenderer.java:83)
	at net.minecraft.client.renderer.ItemRenderer.func_187457_a(ItemRenderer.java:478)
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:365)
	at net.minecraft.client.renderer.EntityRenderer.renderHand(EntityRenderer.java:1038)
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:982)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1918)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1574)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Scythe_Ironclaw'/255, l='MpServer', x=-51.70, y=11.00, z=-74.51]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-384,64,-51), Chunk: (at 0,4,13 in -24,-4; contains blocks -384,0,-64 to -369,255,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 845104 game time, 845104 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 106 total; [EntityPlayerSP['Scythe_Ironclaw'/255, l='MpServer', x=-51.70, y=11.00, z=-74.51], EntityPig['Pig'/259, l='MpServer', x=3.66, y=62.24, z=-144.83], EntityDweller['Dweller'/779, l='MpServer', x=19.50, y=13.00, z=-43.50], EntityPig['Pig'/269, l='MpServer', x=-13.50, y=64.00, z=-138.21], EntityCow['Cow'/270, l='MpServer', x=-91.20, y=63.00, z=-52.60], EntitySheep['Sheep'/271, l='MpServer', x=-87.30, y=66.00, z=-49.51], EntitySheep['Sheep'/272, l='MpServer', x=-102.81, y=66.00, z=-44.50], EntityCow['Cow'/273, l='MpServer', x=-74.78, y=56.00, z=-75.40], EntitySkeleton['Skeleton'/282, l='MpServer', x=-128.50, y=63.00, z=-13.50], EntityCow['Cow'/284, l='MpServer', x=-16.53, y=88.00, z=0.15], EntityPig['Pig'/293, l='MpServer', x=12.55, y=73.00, z=-16.45], EntityPig['Pig'/294, l='MpServer', x=-0.32, y=72.00, z=-25.50], EntityCow['Cow'/297, l='MpServer', x=-6.77, y=78.00, z=-8.52], EntityCow['Cow'/300, l='MpServer', x=8.45, y=81.00, z=0.45], EntityCow['Cow'/306, l='MpServer', x=27.47, y=79.00, z=-3.85], EntityCow['Cow'/307, l='MpServer', x=23.52, y=76.00, z=-13.16], EntityCow['Cow'/308, l='MpServer', x=26.50, y=75.00, z=-15.77], EntityCow['Cow'/309, l='MpServer', x=20.41, y=83.00, z=-3.55], EntitySheep['Sheep'/311, l='MpServer', x=-91.41, y=62.18, z=-39.16], EntitySheep['Sheep'/312, l='MpServer', x=-80.80, y=62.47, z=-37.14], EntityCow['Cow'/313, l='MpServer', x=5.74, y=77.56, z=-0.45], EntityCow['Cow'/314, l='MpServer', x=1.11, y=77.07, z=-0.40], EntityCreeper['Creeper'/317, l='MpServer', x=24.50, y=15.00, z=0.50], EntityZombie['Zombie'/581, l='MpServer', x=-124.50, y=30.00, z=-143.50], EntityCreeper['Creeper'/582, l='MpServer', x=-126.50, y=30.00, z=-143.50], EntityFishClownfish['Clownfish'/329, l='MpServer', x=-114.50, y=61.00, z=-146.50], EntityFishClownfish['Clownfish'/330, l='MpServer', x=-115.50, y=61.00, z=-145.50], EntityPig['Pig'/331, l='MpServer', x=21.49, y=73.00, z=-20.22], EntityPig['Pig'/332, l='MpServer', x=20.26, y=76.00, z=-18.47], EntitySpider['Spider'/333, l='MpServer', x=-131.50, y=16.00, z=-131.50], EntityCow['Cow'/337, l='MpServer', x=-89.50, y=62.17, z=-95.50], EntityCow['Cow'/338, l='MpServer', x=-93.22, y=63.00, z=-80.49], EntitySheep['Sheep'/339, l='MpServer', x=-52.60, y=63.00, z=-126.14], EntityCow['Cow'/340, l='MpServer', x=-54.84, y=63.00, z=-115.58], EntitySkeleton['Skeleton'/345, l='MpServer', x=-131.50, y=17.00, z=-41.50], EntityLatchedRenderer['unknown'/602, l='MpServer', x=-51.70, y=11.00, z=-74.51], EntitySkeleton['Skeleton'/349, l='MpServer', x=-131.50, y=52.00, z=-32.70], EntityBat['Bat'/365, l='MpServer', x=-56.50, y=32.10, z=2.50], EntityBat['Bat'/366, l='MpServer', x=-55.50, y=32.10, z=1.50], EntityCow['Cow'/367, l='MpServer', x=-40.17, y=62.55, z=-115.84], EntityChicken['Chicken'/368, l='MpServer', x=-14.46, y=63.00, z=-153.16], EntityPig['Pig'/369, l='MpServer', x=-7.17, y=62.42, z=-148.47], EntityRabbit['Rabbit'/370, l='MpServer', x=-20.44, y=64.00, z=-136.51], EntityChicken['Chicken'/371, l='MpServer', x=-16.54, y=64.00, z=-138.73], EntityCow['Cow'/372, l='MpServer', x=-114.19, y=64.00, z=-33.42], EntityPig['Pig'/373, l='MpServer', x=-93.54, y=64.00, z=-71.73], EntityCow['Cow'/374, l='MpServer', x=-89.61, y=64.00, z=-67.42], EntitySkeleton['Skeleton'/390, l='MpServer', x=-130.50, y=50.00, z=-26.50], EntityZombie['Zombie'/647, l='MpServer', x=-92.50, y=13.00, z=-131.50], EntityBat['Bat'/392, l='MpServer', x=-131.50, y=50.10, z=-26.50], EntitySkeleton['Skeleton'/648, l='MpServer', x=-95.50, y=13.00, z=-129.50], EntitySkeleton['Skeleton'/393, l='MpServer', x=-131.50, y=52.00, z=-31.92], EntityZombie['Zombie'/394, l='MpServer', x=-131.50, y=50.00, z=-28.50], EntityZombie['Zombie'/395, l='MpServer', x=-130.50, y=50.00, z=-26.50], EntitySlime['Slime'/653, l='MpServer', x=-44.02, y=16.00, z=-100.02], EntityPig['Pig'/405, l='MpServer', x=-13.50, y=74.00, z=-18.67], EntityCow['Cow'/406, l='MpServer', x=-23.81, y=74.00, z=-18.50], EntityCow['Cow'/407, l='MpServer', x=-15.18, y=77.00, z=-14.51], EntityCow['Cow'/408, l='MpServer', x=-8.15, y=73.00, z=-19.53], EntityCow['Cow'/409, l='MpServer', x=-18.81, y=40.00, z=-12.51], EntityCow['Cow'/410, l='MpServer', x=-25.22, y=82.00, z=-8.49], EntityBat['Bat'/411, l='MpServer', x=-101.85, y=22.29, z=-110.46], EntityFishCod['Cod'/412, l='MpServer', x=-98.50, y=37.00, z=-100.50], EntityFishCod['Cod'/413, l='MpServer', x=-99.50, y=37.00, z=-102.50], EntityPig['Pig'/419, l='MpServer', x=-65.16, y=62.46, z=-8.17], EntityPig['Pig'/420, l='MpServer', x=-66.83, y=62.21, z=-13.19], EntityBat['Bat'/421, l='MpServer', x=-91.37, y=14.81, z=-136.54], EntityFishCod['Cod'/426, l='MpServer', x=-87.50, y=61.46, z=-98.31], EntityFishCod['Cod'/427, l='MpServer', x=-84.41, y=61.64, z=-103.43], EntityPig['Pig'/428, l='MpServer', x=-103.55, y=62.67, z=-93.05], EntitySheep['Sheep'/431, l='MpServer', x=22.19, y=66.00, z=-91.49], EntitySkeleton['Skeleton'/433, l='MpServer', x=-128.50, y=22.00, z=-51.50], EntityCreeper['Creeper'/434, l='MpServer', x=-128.50, y=22.00, z=-51.50], EntityCow['Cow'/435, l='MpServer', x=-21.59, y=65.00, z=-39.15], EntityBat['Bat'/436, l='MpServer', x=-49.24, y=21.87, z=-13.73], EntityZombie['Zombie'/437, l='MpServer', x=-71.50, y=12.00, z=1.50], EntityZombie['Zombie'/438, l='MpServer', x=-70.50, y=12.00, z=1.50], EntityPig['Pig'/439, l='MpServer', x=-65.76, y=62.54, z=2.86], EntitySheep['Sheep'/440, l='MpServer', x=4.79, y=64.00, z=-120.50], EntityPig['Pig'/441, l='MpServer', x=3.38, y=64.00, z=-114.71], EntityZombie['Zombie'/443, l='MpServer', x=-130.50, y=22.00, z=-106.50], EntitySpider['Spider'/444, l='MpServer', x=-112.50, y=18.00, z=0.50], EntityPig['Pig'/445, l='MpServer', x=-77.51, y=63.00, z=-37.73], EntityCow['Cow'/446, l='MpServer', x=-80.19, y=63.00, z=-43.60], EntitySkeleton['Skeleton'/702, l='MpServer', x=-59.50, y=24.00, z=-4.50], EntityFishClownfish['Clownfish'/447, l='MpServer', x=-118.77, y=61.00, z=-141.58], EntityFishClownfish['Clownfish'/448, l='MpServer', x=-121.28, y=61.41, z=-143.44], EntityFishCod['Cod'/459, l='MpServer', x=-96.50, y=60.00, z=-152.50], EntityFishCod['Cod'/460, l='MpServer', x=-98.50, y=60.00, z=-151.50], EntityFishCod['Cod'/461, l='MpServer', x=-101.50, y=60.00, z=-147.50], EntityFishCod['Cod'/462, l='MpServer', x=-102.50, y=60.00, z=-148.50], EntityFishPufferfish['Pufferfish'/463, l='MpServer', x=-101.50, y=49.00, z=-123.50], EntityFishPufferfish['Pufferfish'/464, l='MpServer', x=-102.50, y=49.00, z=-121.50], EntityFishPufferfish['Pufferfish'/465, l='MpServer', x=-101.50, y=49.00, z=-125.50], EntityMinecartChest['Minecart with Chest'/466, l='MpServer', x=-121.06, y=41.00, z=-98.51], EntityCow['Cow'/467, l='MpServer', x=-73.90, y=62.37, z=-13.88], EntityCow['Cow'/468, l='MpServer', x=-54.44, y=65.00, z=-32.19], EntitySkeleton['Skeleton'/724, l='MpServer', x=-4.50, y=35.00, z=-93.50], EntitySquid['Squid'/469, l='MpServer', x=-96.09, y=48.08, z=-133.38], EntityBat['Bat'/470, l='MpServer', x=-116.15, y=38.39, z=-120.25], EntityFishCod['Cod'/471, l='MpServer', x=-98.50, y=58.00, z=-124.50], EntityFishCod['Cod'/472, l='MpServer', x=-97.50, y=58.00, z=-125.50], EntityFishCod['Cod'/473, l='MpServer', x=-97.50, y=58.00, z=-128.50], EntityFishCod['Cod'/474, l='MpServer', x=-100.50, y=58.00, z=-124.50], EntityCaveSpider['Cave Spider'/500, l='MpServer', x=-57.68, y=34.00, z=-68.77], EntityCaveSpider['Cave Spider'/501, l='MpServer', x=-58.87, y=34.00, z=-68.00]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 302735880 bytes (288 MB) / 2011168768 bytes (1918 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.3.2297 Optifine OptiFine_1.10.2_HD_U_D8 64 mods loaded, 64 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2297.jar) 
	UCHIJAAAA	Forge{12.18.3.2297} [Minecraft Forge] (forge-1.10.2-12.18.3.2297.jar) 
	UCHIJAAAA	AdvancedRocketryCore{1} [Advanced Rocketry] (minecraft.jar) 
	UCHIJAAAA	Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.9.4-1.1.1.2.jar) 
	UCHIJAAAA	thinkbigcore{1.5.8} [§5§m===§r §e§lThink Big Core §5§m===§r] (Think Big Core V1.5.8 - 1.10.2.jar) 
	UCHIJAAAA	adinferos{1.2.4} [§e§k!!§6§k]]§c§kkk§4§lAd Inferos§c§kkk§6§k]]§e§k!!] (Ad Inferos V1.2.4 - 1.10.2.jar) 
	UCHIJAAAA	IC2{2.6.210-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.210-ex110.jar) 
	UCHIJAAAA	advanced_machines{60.0.4} [Advanced Machines] (Advanced Machines-60.0.4.jar) 
	UCHIJAAAA	advanced_solar_panels{4.0.4} [Advanced Solar Panels] (Advanced Solar Panels-4.0.4.jar) 
	UCHIJAAAA	libVulpes{0.2.3.} [libVulpes] (LibVulpes-1.10.2-0.2.3-universal.jar) 
	UCHIJAAAA	advancedRocketry{1.2.0c} [Advanced Rocketry] (AdvancedRocketry-1.10.2-1.2.0c.jar) 
	UCHIJAAAA	aether{1.10.2-r1} [Aether II] (AetherII-1.10.2-r1.git-b02ce56.jar) 
	UCHIJAAAA	Aroma1997CoreHelper{1.1.1.2} [Aroma1997Core|Helper] (Aroma1997Core-1.9.4-1.1.1.2.jar) 
	UCHIJAAAA	Aroma1997sDimension{1.0} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.9.4-1.2.0.7.jar) 
	UCHIJAAAA	astralsorcery{1.4.1} [Astral Sorcery] (astralsorcery-1.4.1.jar) 
	UCHIJAAAA	Psi{r1.0-42} [Psi] (Psi-r1.0-42.jar) 
	UCHIJAAAA	Quark{r1.1-70} [Quark] (Quark-r1.1-70.jar) 
	UCHIJAAAA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJAAAA	Baubles{1.3.11} [Baubles] (Baubles-1.10.2-1.3.11.jar) 
	UCHIJAAAA	baublesstuff{3.0.2} [Baubles Stuff] (baublesstuff-3.0.2.jar) 
	UCHIJAAAA	betterthanmending{@VERSION@} [Better Than Mending] (BetterThanMending-0.10.0.jar) 
	UCHIJAAAA	cavern{1.7.4} [Cavern] (Cavern_1.10.2-v1.7.4.jar) 
	UCHIJAAAA	clarity{1.0} [Clarity] (clarity-1.0.jar) 
	UCHIJAAAA	cnoapm{1.0 by Dot_Silver} [Craftable Notch Apple Mod - MCVersion 1.10.2] (cnoapm-mcv1.10.2.jar) 
	UCHIJAAAA	compactsolars{1.10.2-5.0.9.332} [Compact Solar Arrays] (CompactSolars-1.10.2-5.0.9.332-universal.jar) 
	UCHIJAAAA	craftingtweaks{6.1.16} [Crafting Tweaks] (CraftingTweaks_1.10.2-6.1.16.jar) 
	UCHIJAAAA	crossbowmod{1.3} [Crossbow Mod] (crossbowmod-1.3.jar) 
	UCHIJAAAA	dirt2path{1.6.1} [Dirt2Path] (dirt2path-1.6.1.jar) 
	UCHIJAAAA	double_jump{1.0.1} [DoubleJump] (DoubleJump-1.10.2-1.0.0.jar) 
	UCHIJAAAA	DurabilityShow{3.1.1} [Durability Show] (Durability Show-1.9.4-3.1.1.jar) 
	UCHIJAAAA	endercompass{1.2.3.2} [Ender Compass] (EnderCompass-1.9.x-1.2.3.2.jar) 
	UCHIJAAAA	shetiphiancore{3.3.9} [ShetiPhian-Core] (shetiphiancore-1.10.0-3.3.9.jar) 
	UCHIJAAAA	endertanks{1.4.13} [EnderTanks] (endertanks-1.10.0-1.4.13.jar) 
	UCHIJAAAA	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UCHIJAAAA	forgeendertech{1.10.2-1.3.3.0} [Forge Endertech] (ForgeEndertech-1.10.2-1.3.3.0-build.0055.jar) 
	UCHIJAAAA	grapple_hooks{1.0.8} [Grapple Hooks] (Grapple-Hooks-1.10.2-1.0.8.jar) 
	UCHIJAAAA	gravisuite{3.0.1} [Gravitation Suite] (Gravitation Suite-3.0.1.jar) 
	UCHIJAAAA	ichunutil{6.3.2} [iChunUtil] (iChunUtil-1.10.2-6.3.2.jar) 
	UCHIJAAAA	gravitygun{6.0.1} [GravityGun] (GravityGun-1.10.2-6.0.1.jar) 
	UCHIJAAAA	itank{1.1.0-1.10.2} [itank] (ITank-1.1.0-1.10.2.jar) 
	UCHIJAAAA	JEI{3.14.7.419} [Just Enough Items] (jei_1.10.2-3.14.7.419.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.4.6} [JourneyMap] (journeymap-1.10.2-5.4.6.jar) 
	UCHIJAAAA	jaff{1.5.2_for_1.10.2} [Just a Few Fish] (JustAFewFish-1.5.2_for_1.10.2.jar) 
	UCHIJAAAA	jeresources{0.5.9.3} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.9.3.jar) 
	UCHIJAAAA	labyrinth{${version}} [Daedalus' Labyrinth] (Labyrinth-1.4.jar) 
	UCHIJAAAA	craftelytra{1.1} [Craftable Elytra] (modid-1.1-1.10.2.jar) 
	UCHIJAAAA	portalgun{6.0.1} [PortalGun] (PortalGun-1.10.2-6.0.1.jar) 
	UCHIJAAAA	ProjectE{1.10.2-PE1.3.0} [ProjectE] (ProjectE-1.10.2-PE1.3.0.jar) 
	UCHIJAAAA	reborncore{2.13.6.142} [RebornCore] (RebornCore-1.10.2-2.13.6.142-universal.jar) 
	UCHIJAAAA	reborncore-mcmultipart{2.13.6.142} [reborncore-MCMultiPart] (RebornCore-1.10.2-2.13.6.142-universal.jar) 
	UCHIJAAAA	simplevoidworld{1.1.0.4} [SimpleVoidWorld] (Simple-Void-World-1.10.2-1.1.0.4-universal.jar) 
	UCHIJAAAA	soundfilters{0.9_for_1.9} [Sound Filters] (SoundFilters-0.9_for_1.9.4.jar) 
	UCHIJAAAA	spartanshields{1.3} [Spartan Shields] (SpartanShields-1.10.2-1.3.jar) 
	UCHIJAAAA	subcommonlib{1.1.3.0} [Subaraki's Common Library] (sublib-1.10.2-1.1.3.0.jar) 
	UCHIJAAAA	telepads{1.10.2 v1.0.1.2} [Telepads] (telepads-1.10.2-1.0.1.2.jar) 
	UCHIJAAAA	teletoro{1.10.2-20.1} [TeleToro] (teletoro-1.10.2-20.1.jar) 
	UCHIJAAAA	beneath{1.2.0} [The Beneath] (The Beneath-1.10.2-1.2.0.jar) 
	UCHIJAAAA	totemic{1.10.2-0.8.3} [Totemic] (Totemic-1.10.2-0.8.3.jar) 
	UCHIJAAAA	wanionlib{1.10.2-1.3} [WanionLib] (WanionLib-1.10.2-1.3.jar) 
	UCHIJAAAA	wearablebackpacks{1.6.2} [Wearable Backpacks] (WearableBackpacks-1.10.2-1.6.2.jar) 
	UCHIJAAAA	xpplus{1.0} [XP-Plus] (xpplus-1.02.jar) 
	UCHIJAAAA	adfinders{1.10.2-1.1.2.0} [Advanced Finders] (AdFinders-1.10.2-1.1.2.0-build.0055.jar) 
	UCHIJAAAA	unidict{1.10.2-2.8} [UniDict] (UniDict-1.10.2-2.8.jar) 
	Loaded coremods (and transformers): 
CoreMod (Aroma1997Core-1.9.4-1.1.1.2.jar)
  
IC2core (industrialcraft-2-2.6.210-ex110.jar)
  
AdvancedRocketryPlugin (AdvancedRocketry-1.10.2-1.2.0c.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
DummyPlugin (ForgeEndertech-1.10.2-1.3.3.0-build.0055.jar)
  
ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.9.jar)
  shetiphian.core.asm.ClassTransformer
LoadingPlugin (Quark-r1.1-70.jar)
  vazkii.quark.base.asm.ClassTransformer
RebornCoreASM (RebornCore-1.10.2-2.13.6.142-universal.jar)
  reborncore.mixin.transformer.MixinTransformer
LoadingPlugin (AdFinders-1.10.2-1.1.2.0-build.0055.jar)
  com.endertech.minecraft.mods.adfinders.core.RenderTransformer
AstralCore (astralsorcery-1.4.1.jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1151.0' Renderer: 'AMD Radeon HD 6620G'
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 2.13.6.142
		Mixin Status: 1
		Runtime Debofucsation 1
		RenderEngine: 1
	Launched Version: forge-12.18.3.2297
	LWJGL: 2.9.4
	OpenGL: AMD Radeon HD 6620G GL version 4.5.13399 Compatibility Profile Context 15.201.1151.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A8-3500M APU with Radeon(tm) HD Graphics

**Comment by ghost** [comment]
Still happens as of 1.12.2
