### ISSUE TITLE
PortalGun-1.10.2-6.0.1 crash on 2nd portal shot

### ISSUE THREAD

**Issue by ReporterDXD** [iChun/IssueTracker-Mods#96]
I have other mod installed and using PortalGun but everytime i shot 2nd portal it crash the game

my mod are
ShinColle-1.10.2.3.2
journeymap-1.10.2-5.4.6
iChunUtil-1.10.2-6.3.2
Harvest-Festival-1.10.2-0.6.0-218
OptiFine_1.10.2_HD_U_D8
cfm-4.1.2-mc1.10.2

crash report
---- Minecraft Crash Report ----

WARNING: coremods are present:
  HFTransformer (Harvest-Festival-1.10.2-0.6.0-218.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 14/06/17 20:59
Description: Batching chunks

java.lang.NoSuchFieldError: field_189564_r
	at me.ichun.mods.ichunutil.common.module.worldportals.client.render.world.chunk.RenderChunkWorldPortal.func_178581_b(RenderChunkWorldPortal.java:71)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:119)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:47)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Ideon'/410, l='MpServer', x=-373,24, y=75,11, z=123,18]]
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-137,64,240), Chunk: (at 7,4,0 in -9,15; contains blocks -144,0,240 to -129,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 289605 game time, 181287 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 28 total; [EntitySkeleton['Skeleton'/448, l='MpServer', x=-384,50, y=24,00, z=170,50], EntityCow['Cow'/385, l='MpServer', x=-344,17, y=64,00, z=77,25], EntityLatchedRenderer['unknown'/514, l='MpServer', x=-373,24, y=75,11, z=123,18], EntityVillager['Villager'/387, l='MpServer', x=-339,65, y=75,00, z=108,53], EntityVillager['Villager'/388, l='MpServer', x=-339,47, y=74,33, z=105,67], EntityIronGolem['Iron Golem'/389, l='MpServer', x=-337,13, y=75,00, z=100,13], EntityVillager['Villager'/390, l='MpServer', x=-339,21, y=74,94, z=107,61], EntityVillager['Villager'/18, l='MpServer', x=-330,70, y=71,94, z=95,40], EntityIronGolem['Iron Golem'/19, l='MpServer', x=-330,05, y=73,00, z=99,96], EntityVillager['Villager'/20, l='MpServer', x=-331,07, y=73,50, z=99,73], EntityVillager['Villager'/21, l='MpServer', x=-331,72, y=74,00, z=99,94], EntityVillager['Villager'/22, l='MpServer', x=-335,50, y=73,00, z=100,29], EntityIronGolem['Iron Golem'/23, l='MpServer', x=-336,02, y=75,25, z=106,89], EntityCarrierWo['Standard Carrier Wo-Class'/476, l='MpServer', x=-384,64, y=68,00, z=113,14], EntityLatchedRenderer['unknown'/477, l='MpServer', x=-373,24, y=75,11, z=123,18], EntityIronGolem['X member'/349, l='MpServer', x=-346,43, y=71,00, z=121,68], EntityVillager['Villager'/350, l='MpServer', x=-345,38, y=71,00, z=123,36], EntityVillager['Villager'/351, l='MpServer', x=-341,60, y=73,00, z=118,49], EntityVillager['Villager'/352, l='MpServer', x=-342,50, y=71,00, z=136,40], EntityHorse['Horse'/355, l='MpServer', x=-341,36, y=71,94, z=94,32], EntityPlayerSP['Ideon'/410, l='MpServer', x=-373,24, y=75,11, z=123,18], EntityLatchedRenderer['unknown'/425, l='MpServer', x=8,50, y=65,00, z=8,50], EntityItemFrame['entity.ItemFrame.name'/361, l='MpServer', x=-358,50, y=71,50, z=171,03], EntityLatchedRenderer['unknown'/426, l='MpServer', x=-373,24, y=75,11, z=123,18], EntityLatchedRenderer['unknown'/427, l='MpServer', x=-373,24, y=75,11, z=123,18], EntityCreeper['Creeper'/494, l='MpServer', x=-380,50, y=24,00, z=165,50], EntityHorse['Horse'/505, l='MpServer', x=-413,87, y=71,00, z=88,11], EntityCow['Cow'/506, l='MpServer', x=-415,14, y=71,00, z=92,82]]
	Retry entities: 4 total; [EntityLatchedRenderer['unknown'/425, l='MpServer', x=8,50, y=65,00, z=8,50], EntityLatchedRenderer['unknown'/426, l='MpServer', x=-373,24, y=75,11, z=123,18], EntityLatchedRenderer['unknown'/427, l='MpServer', x=-373,24, y=75,11, z=123,18], EntityLatchedRenderer['unknown'/477, l='MpServer', x=-373,24, y=75,11, z=123,18]]
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:57)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 143786920 bytes (137 MB) / 1037959168 bytes (989 MB) up to 1037959168 bytes (989 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.3.2316 Optifine OptiFine_1.10.2_HD_U_D8 12 mods loaded, 12 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2316.jar) 
	UCHIJAAAA	Forge{12.18.3.2316} [Minecraft Forge] (forge-1.10.2-12.18.3.2316.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJAAAA	digimobs{0.9.8f} [Digimobs] ($ROVYFVH.jar) 
	UCHIJAAAA	cfm{4.1.2} [MrCrayfish's Furniture Mod] (cfm-4.1.2-mc1.10.2.jar) 
	UCHIJAAAA	ichunutil{6.3.2} [iChunUtil] (iChunUtil-1.10.2-6.3.2.jar) 
	UCHIJAAAA	gravitygun{6.0.1} [GravityGun] (GravityGun-1.10.2-6.0.1.jar) 
	UCHIJAAAA	harvestfestival{0.6.0} [Harvest Festival] (Harvest-Festival-1.10.2-0.6.0-218.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.4.6} [JourneyMap] (journeymap-1.10.2-5.4.6.jar) 
	UCHIJAAAA	portalgun{6.0.1} [PortalGun] (PortalGun-1.10.2-6.0.1.jar) 
	UCHIJAAAA	shincolle{1.10.2.3.2} [Shinkeiseikan Collection] (ShinColle-1.10.2.3.2.jar) 
	Loaded coremods (and transformers): 
HFTransformer (Harvest-Festival-1.10.2-0.6.0-218.jar)
  joshie.harvest.asm.HFTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Launched Version: 1.10.2-forge1.10.2-12.18.3.2316
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x AMD Athlon(tm) 64 X2 Dual Core Processor 5200+
	OptiFine Version: OptiFine_1.10.2_HD_U_D8
	Render Distance Chunks: 4
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.3.0
	OpenGlRenderer: GeForce GT 240/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 2

**Comment by iChun** [comment]
See through portals aren't compatible with Optifine. Either turn them off
or remove one of the mods.

**Comment by ReporterDXD** [comment]
Guess have to remove portal gun for now

**Comment by InjuredWolf** [comment]
Or just disable the see-through-portals option.
